#cloud:
#  aws:
#    credentials:
#      access-key: AKIA2QOST6QV36DJBS6M
#      secret-key: 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
#    region:
#      static: sa-east-1
#    stack:
#      auto: false
#
#application:
#  bucket:
#    name: myawsbucketduds
#
#
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB
#
#server:
#  port: 8080

amazonProperties:
  endpointUrl: https://s3.sa-east-1.amazonaws.com
  accessKey: AKIA2QOST6QV36DJBS6M
  secretKey: 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
  bucketName: myawsbucketduds