cloud:
<<<<<<< HEAD
  aws:
    credentials:
      access-key: AKIA2QOST6QV3TJVWCWI
      secret-key: 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
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: myawsbucketduds


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
=======
 aws:
   credentials:
     access-key:
     secret-key:
   region:
     static: sa-east-1
   stack:
     auto: false

application:
 bucket:
   name: 


spring:
 servlet:
   multipart:
     enabled: true
     file-size-threshold: 2MB
     max-file-size: 5MB
     max-request-size: 10MB

server:
 port: 8080
>>>>>>> 6e5d2a0393f0c3cc728c23fbc9b271056e5e64f7

