cloud:
  aws:
    credentials:
      access-key: AKIA2QOST6QVRY3V6RX7
      secret-key: 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
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: myawsbucketduds


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080